---

- name: Add UFW to HAProxy Servers
  ansible.builtin.package:
    pkg:
    - ufw
  register: package_status
  until: package_status is success
  delay: 6
  retries: 10

- name: Set up UFW rules from dictionary
  community.general.ufw:
    rule: "{{ item.rule | default('allow') }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto | default('any') }}"
    from_ip: "{{ item.from_ip | default('any') }}"
    insert_relative_to: "{{ item.insert_relative_to | default('zero') }}"
    direction: "{{ item.direction | default('in') }}"
  loop: "{{ ufw_allow_dict }}"

- name: UFW default allow outgoing traffic on HAProxy Servers
  community.general.ufw:
    policy: allow
    direction: outgoing

- name: UFW default deny incoming traffic on HAProxy Servers
  community.general.ufw:
    policy: deny
    direction: incoming

- name: Enable Firewall on HAProxy Servers
  community.general.ufw:
    state: enabled
